-- Location Architecture V2 Phase 1 -- upgrade-path / legacy-preservation.
--
-- SUPERSEDED by Architecture V2 Phase 2 (20260903120000_location_phase2_cutover.sql). This file
-- originally proved that create_location/update_location/delete_location/create_scene/
-- get_project_content, unmodified in behavior by the Phase 1 migration, still read and wrote
-- `location_projects_legacy_v1` end-to-end while the new Foundation tables stayed untouched.
-- Phase 2 deliberately inverts that contract on purpose: those RPCs now read/write
-- `public.locations` + `public.project_locations`, and `location_projects_legacy_v1` is
-- read-only. Rewriting this file's assertions in place would just duplicate
-- supabase/tests/location_phase2_cutover.sql (the current-model RPC contract) and
-- supabase/tests/ci/location_phase2_00_pre_seed.sql / _01_post_verify.sql (the true legacy ->
-- new-model upgrade path, run against the migration chain with only
-- 20260903120000_location_phase2_cutover.sql excluded -- the Phase 2 analogue of what this file
-- used to do for Phase 1). Left as an inert placeholder, rather than deleted, so the historical
-- Phase 1 guarantee stays discoverable by filename/git-blame; it intentionally contains no
-- assertions and is a no-op when picked up by a `for f in supabase/tests/*.sql` regression loop.
