const CHARACTER_LINK_CATEGORIES=Object.freeze({family:"Родство",marriage:"Брак / партнёрство",legal:"Юридические",guardianship:"Опека",other:"Другое"});
const CHARACTER_LINK_TYPES=Object.freeze([
  ["mother","Мать","family","parent_child"],["father","Отец","family","parent_child"],["parent","Родитель","family","parent_child"],["son","Сын","family","parent_child"],["daughter","Дочь","family","parent_child"],["child","Ребёнок","family","parent_child"],
  ["brother","Брат","family","sibling"],["sister","Сестра","family","sibling"],["sibling","Сиблинг","family","sibling"],["stepbrother","Сводный брат","family","sibling"],["stepsister","Сводная сестра","family","sibling"],["stepsibling","Сводный сиблинг","family","sibling"],
  ["grandfather","Дедушка","family","parent_child"],["grandmother","Бабушка","family","parent_child"],["grandparent","Дед/бабушка","family","parent_child"],["grandson","Внук","family","parent_child"],["granddaughter","Внучка","family","parent_child"],["grandchild","Внук/внучка","family","parent_child"],
  ["uncle","Дядя","family","other"],["aunt","Тётя","family","other"],["nephew","Племянник","family","other"],["niece","Племянница","family","other"],["cousin_male","Кузен","family","other"],["cousin_female","Кузина","family","other"],["cousin","Кузен/кузина","family","other"],
  ["spouse","Супруг","marriage","partnership"],["spouse_female","Супруга","marriage","partnership"],["husband","Муж","marriage","partnership"],["wife","Жена","marriage","partnership"],["partner","Партнёр","marriage","partnership"],["former_spouse","Бывший супруг","marriage","partnership"],["former_spouse_female","Бывшая супруга","marriage","partnership"],["former_partner","Бывший партнёр","marriage","partnership"],
  ["adoptive_parent","Усыновитель","legal","parent_child"],["adopted_child","Усыновлённый ребёнок","legal","parent_child"],["foster_parent","Приёмный родитель","legal","parent_child"],["foster_child","Приёмный ребёнок","legal","parent_child"],
  ["guardian","Опекун","guardianship","guardianship"],["ward","Подопечный","guardianship","guardianship"],["stepfather","Отчим","family","parent_child"],["stepmother","Мачеха","family","parent_child"],["stepson","Пасынок","family","parent_child"],["stepdaughter","Падчерица","family","parent_child"],["custom","Собственная формулировка","other","other"]
].map(([value,label,category,structureKind])=>({value,label,category,structureKind})));
const typeByValue=value=>CHARACTER_LINK_TYPES.find(item=>item.value===value);
function isKnownCharacterLinkType(value){return !!typeByValue(value)}
function normalizeCharacterLink(value){
  const source=safeOwnCopy(value&&typeof value==="object"?value:{}),type=String(source.type||""),reverseType=String(source.reverseType||"");
  return {...source,id:String(source.id||""),fromCharacterId:String(source.fromCharacterId||""),toCharacterId:String(source.toCharacterId||""),category:String(source.category||"other"),type,reverseType,customLabel:String(source.customLabel||""),reverseCustomLabel:String(source.reverseCustomLabel||""),notes:String(source.notes||""),structureKind:String(source.structureKind||typeByValue(type)?.structureKind||"other"),metadata:safeOwnCopy(source.metadata&&typeof source.metadata==="object"?source.metadata:{})};
}
function characterLinkLabel(link,characterId){const forward=link.fromCharacterId===characterId,type=forward?link.type:link.reverseType,custom=forward?link.customLabel:link.reverseCustomLabel;return type==="custom"?custom:type}
function characterLinkDisplayLabel(link,characterId){const forward=link.fromCharacterId===characterId,type=forward?link.reverseType:link.type,custom=forward?link.reverseCustomLabel:link.customLabel,value=type==="custom"?custom:type;return typeByValue(value)?.label||value}
function sameSemanticLink(a,b){return (a.fromCharacterId===b.fromCharacterId&&a.toCharacterId===b.toCharacterId&&a.type===b.type&&a.reverseType===b.reverseType&&a.customLabel===b.customLabel&&a.reverseCustomLabel===b.reverseCustomLabel)||(a.fromCharacterId===b.toCharacterId&&a.toCharacterId===b.fromCharacterId&&a.type===b.reverseType&&a.reverseType===b.type&&a.customLabel===b.reverseCustomLabel&&a.reverseCustomLabel===b.customLabel)}
function isDuplicateCharacterLink(candidate,links,ignoreId=""){const link=normalizeCharacterLink(candidate);return links.some(item=>item.id!==ignoreId&&sameSemanticLink(link,normalizeCharacterLink(item)))}
function removeCharacterLinksForCharacter(project,characterId){project.characterLinks=(project.characterLinks||[]).filter(link=>link.fromCharacterId!==characterId&&link.toCharacterId!==characterId)}
function linksForCharacter(characterId,links=profileDraftCharacterLinks){return links.filter(link=>link.fromCharacterId===characterId||link.toCharacterId===characterId)}
function renderProfileCharacterLinks(){
  const root=document.getElementById("profileCharacterLinks");if(!root)return;const links=linksForCharacter(profileEditingId);
  root.innerHTML=links.map(link=>{const other=link.fromCharacterId===profileEditingId?link.toCharacterId:link.fromCharacterId;return `<div class="character-link-row" data-link-id="${esc(link.id)}"><div><strong>${esc(characterName(other))}</strong> — ${esc(characterLinkDisplayLabel(link,profileEditingId))}${link.notes?`<div class="profile-note">${esc(link.notes)}</div>`:""}</div><div class="character-link-actions"><button type="button" aria-label="Изменить связь с ${esc(characterName(other))}" onclick="openCharacterLinkEditor('${jsq(link.id)}')">Изменить</button><button type="button" class="danger" aria-label="Удалить связь с ${esc(characterName(other))}" onclick="deleteDraftCharacterLink('${jsq(link.id)}')">Удалить</button></div></div>`}).join("")||'<p class="profile-note">Связи пока не добавлены.</p>';
}
function typeOptions(selected=""){return CHARACTER_LINK_TYPES.map(item=>`<option value="${item.value}" ${item.value===selected?"selected":""}>${item.label}</option>`).join("")}
function syncCharacterLinkCustomFields(){document.getElementById("characterLinkCustomFields").hidden=document.getElementById("characterLinkType").value!=="custom";document.getElementById("characterLinkReverseCustomFields").hidden=document.getElementById("characterLinkReverseType").value!=="custom"}
function openCharacterLinkEditor(id=""){
  characterLinkEditingId=id;const existing=profileDraftCharacterLinks.find(link=>link.id===id),link=existing?(existing.fromCharacterId===profileEditingId?existing:{...existing,fromCharacterId:profileEditingId,toCharacterId:existing.fromCharacterId,type:existing.reverseType,reverseType:existing.type,customLabel:existing.reverseCustomLabel,reverseCustomLabel:existing.customLabel}):{fromCharacterId:profileEditingId,toCharacterId:"",category:"family",type:"mother",reverseType:"child",customLabel:"",reverseCustomLabel:"",notes:""};
  document.getElementById("characterLinkEditorTitle").textContent=existing?"Изменить связь":"Добавить связь";
  document.getElementById("characterLinkTarget").innerHTML=data.characters.filter(c=>c.id!==profileEditingId).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join("");
  for(const [id,value] of [["characterLinkTarget",link.toCharacterId],["characterLinkCategory",link.category],["characterLinkScope",link.scope||"project"]])document.getElementById(id).value=value;
  document.getElementById("characterLinkScopeField").hidden=!isCloudWorkspace();document.getElementById("characterLinkScope").disabled=!!existing;
  document.getElementById("characterLinkType").innerHTML=typeOptions(link.type);document.getElementById("characterLinkReverseType").innerHTML=typeOptions(link.reverseType);
  document.getElementById("characterLinkCustomLabel").value=link.customLabel||"";document.getElementById("characterLinkReverseCustomLabel").value=link.reverseCustomLabel||"";document.getElementById("characterLinkNotes").value=link.notes||"";document.getElementById("characterLinkError").textContent="";syncCharacterLinkCustomFields();showModal("characterLinkModal",{initialFocus:"#characterLinkTarget"});trackerFor("characterLinkModal").captureInitialState();
}
function saveDraftCharacterLink(){
  const old=profileDraftCharacterLinks.find(link=>link.id===characterLinkEditingId),from=profileEditingId,to=document.getElementById("characterLinkTarget").value,type=document.getElementById("characterLinkType").value;
  const link=normalizeCharacterLink({...old,id:old?.id||makeId("character-link"),scope:document.getElementById("characterLinkScope").value,fromCharacterId:from,toCharacterId:to,category:document.getElementById("characterLinkCategory").value,type,reverseType:document.getElementById("characterLinkReverseType").value,customLabel:document.getElementById("characterLinkCustomLabel").value.trim(),reverseCustomLabel:document.getElementById("characterLinkReverseCustomLabel").value.trim(),notes:document.getElementById("characterLinkNotes").value.trim(),structureKind:typeByValue(type)?.structureKind||"other"});
  const error=!to?"Выберите персонажа.":from===to?"Нельзя связать персонажа с самим собой.":link.type==="custom"&&!link.customLabel?"Введите прямое название связи.":link.reverseType==="custom"&&!link.reverseCustomLabel?"Введите обратное название связи.":isDuplicateCharacterLink(link,profileDraftCharacterLinks,old?.id)?"Такая логическая связь уже существует.":"";
  if(error){document.getElementById("characterLinkError").textContent=error;return}
  if(old)profileDraftCharacterLinks[profileDraftCharacterLinks.indexOf(old)]=link;else profileDraftCharacterLinks.push(link);trackerFor("characterLinkModal").captureInitialState();forceHideModal("characterLinkModal");renderProfileCharacterLinks();syncBeforeUnload();
}
function deleteDraftCharacterLink(id){profileDraftCharacterLinks=profileDraftCharacterLinks.filter(link=>link.id!==id);renderProfileCharacterLinks();syncBeforeUnload()}
Object.assign(globalThis,{CHARACTER_LINK_CATEGORIES,CHARACTER_LINK_TYPES,normalizeCharacterLink,isKnownCharacterLinkType,characterLinkLabel,characterLinkDisplayLabel,isDuplicateCharacterLink,removeCharacterLinksForCharacter,linksForCharacter,renderProfileCharacterLinks,openCharacterLinkEditor,saveDraftCharacterLink,deleteDraftCharacterLink,syncCharacterLinkCustomFields});
export {CHARACTER_LINK_CATEGORIES,CHARACTER_LINK_TYPES,normalizeCharacterLink,isKnownCharacterLinkType,characterLinkLabel,characterLinkDisplayLabel,isDuplicateCharacterLink,removeCharacterLinksForCharacter,linksForCharacter};
