import {createRequire} from "node:module";
const require=createRequire("C:/Users/tadan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/"),{chromium}=require("playwright");
const base=process.env.AUTHOR_WORKSPACE_URL||"http://127.0.0.1:8000/author-workspace/",emailA=process.env.CLOUD_TEST_EMAIL,passwordA=process.env.CLOUD_TEST_PASSWORD,emailB=process.env.CLOUD_TEST_USER_B_EMAIL,passwordB=process.env.CLOUD_TEST_USER_B_PASSWORD;
if(!emailA||!passwordA||!emailB||!passwordB){console.log("authenticated cross-user storage test skipped: credentials missing");process.exit(0)}
const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"}),contexts=[];const assert=(v,m)=>{if(!v)throw new Error(m)};
async function login(email,password){const context=await browser.newContext();contexts.push(context);const page=await context.newPage();page.setDefaultTimeout(20000);await page.goto(base,{waitUntil:"networkidle"});await page.waitForSelector("#authScreen:not([hidden])");await page.fill("#authEmail",email);await page.fill("#authPassword",password);await page.click("#signInButton");try{await page.waitForSelector("#projectsScreen:not([hidden])")}catch(error){const message=await page.locator("#authMessage").textContent();throw new Error(`temporary authenticated login failed: ${message||"no auth message"}`)}return page}
const setup=async(page,label)=>page.evaluate(async label=>{const owner=cloudState.session.user.id,project=await cloudState.api.createProject({ownerId:owner,title:`AW storage security ${label}`}),created=await cloudState.characterApi.createCharacterAndAttach(project.id,0,{name:`Storage ${label}`,baseProfile:{}},{}),character=created.data.character,pc=created.data.project_character,photoId=crypto.randomUUID(),bytes=new TextEncoder().encode(`<svg xmlns="http://www.w3.org/2000/svg" width="20" height="40"><rect width="20" height="40" fill="${label==='A'?'tomato':'navy'}"/></svg>`),file=new File([bytes],`${label}.png`,{type:"image/png"}),photo={id:photoId,crop:{x:.5,y:.5,zoom:1}},uploaded=await cloudState.imageApi.uploadImage({characterId:character.id,photoId,file,photo,scope:"global",expectedRevision:character.revision,isPrimary:true});return {projectId:project.id,characterId:character.id,projectCharacterId:pc.id,photoId,path:uploaded.storagePath,uploadOk:uploaded.ok}},label);
const rawClient=async(page,fn,arg)=>page.evaluate(async({source,arg})=>{const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/+esm"),client=createClient("https://crchibwumcuuqhkabmfj.supabase.co","sb_publishable_XF0Jk1qKpK4OgW8NAyaj7g_IuAdH8RT");return (0,eval)(`(${source})`)(client,arg)}, {source:fn.toString(),arg});
let a,b,A,B,report;
try{
  a=await login(emailA,passwordA);A=await setup(a,"A");assert(A.uploadOk,"User A own upload failed");
  b=await login(emailB,passwordB);B=await setup(b,"B");assert(B.uploadOk,"User B own upload failed");
  const selectBlocked=await rawClient(b,async(client,path)=>{const r=await client.storage.from("character-images").download(path);return !!r.error},A.path);
  const signedBlocked=await rawClient(b,async(client,path)=>{const r=await client.storage.from("character-images").createSignedUrl(path,60);return !!r.error&&!r.data?.signedUrl},A.path);
  const insertBlocked=await rawClient(b,async(client,path)=>{const r=await client.storage.from("character-images").upload(path.replace(/original\.png$/,"foreign.png"),new Blob(["x"],{type:"image/png"}),{upsert:false});return !!r.error},A.path);
  const updateBlocked=await rawClient(b,async(client,path)=>{const r=await client.storage.from("character-images").upload(path,new Blob(["replace"],{type:"image/png"}),{upsert:true});return !!r.error},A.path);
  const deleteAttempt=await rawClient(b,async(client,path)=>{const r=await client.storage.from("character-images").remove([path]);return {error:!!r.error,removed:(r.data||[]).length}},A.path);
  const aStillReads=await rawClient(a,async(client,path)=>{const r=await client.storage.from("character-images").download(path);return !r.error&&r.data?.size>0},A.path);
  const metadataBlocked=await b.evaluate(async A=>{const result=await cloudState.imageApi.listImages(A.characterId,A.projectCharacterId),rpc=await cloudState.characterApi.attachProjectCharacter(A.projectId,A.characterId,0,{});return {listCode:result.code,rpcCode:rpc.code}},A);
  const directMetadataBlocked=await rawClient(b,async(client,A)=>{const id=crypto.randomUUID(),r=await client.rpc("create_character_image",{image_id:id,character_id:A.characterId,project_character_id:null,storage_path:A.path,mime_type:"image/png",crop:{},alt:"",caption:"",sort_order:0,is_primary:false,metadata:{},image_scope:"global",expected_revision:0,idempotency_key:id});return r.data?.code||r.error?.code||"UNKNOWN"},A);
  const reverseReadBlocked=await rawClient(a,async(client,path)=>{const r=await client.storage.from("character-images").download(path);return !!r.error},B.path);
  assert(selectBlocked&&signedBlocked&&insertBlocked&&updateBlocked&&aStillReads,"User B Storage isolation failed");assert(deleteAttempt.error||deleteAttempt.removed===0,"User B delete reported removed object");assert(metadataBlocked.listCode==="NOT_FOUND"&&metadataBlocked.rpcCode==="NOT_FOUND"&&["NOT_FOUND","VALIDATION_ERROR"].includes(directMetadataBlocked),"cross-owner DB identity isolation failed");assert(reverseReadBlocked,"User A read User B object");
  report={selectBlocked,signedBlocked,insertBlocked,updateBlocked,deleteBlocked:true,metadataBlocked:true,foreignIdsBlocked:true,reverseReadBlocked};
}finally{
  for(const [page,state] of [[a,A],[b,B]])if(page&&state)await rawClient(page,async(client,s)=>{await client.storage.from("character-images").remove([s.path]);await client.from("character_images").delete().eq("id",s.photoId);await client.from("projects").delete().eq("id",s.projectId);await client.from("characters").delete().eq("id",s.characterId);await client.auth.signOut();return true},state).catch(()=>{});
  for(const context of contexts)await context.close();await browser.close();
}
console.log(JSON.stringify({ok:true,...report}));
