import {createRequire} from "node:module";import crypto from "node:crypto";
const require=createRequire("C:/Users/tadan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/"),{chromium}=require("playwright");
const base=process.env.AUTHOR_WORKSPACE_URL||"http://127.0.0.1:8000/author-workspace/",email=process.env.CLOUD_TEST_EMAIL,password=process.env.CLOUD_TEST_PASSWORD;
if(!email||!password){console.log("cloud character images real-browser test skipped: credentials are not configured");process.exit(0)}
const title=`AW images ${crypto.randomBytes(7).toString("hex")}`,browser=await chromium.launch({headless:true,executablePath:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"}),contexts=[];
const assert=(v,m)=>{if(!v)throw new Error(m)};async function login(){const c=await browser.newContext();contexts.push(c);const p=await c.newPage();p.setDefaultTimeout(20000);await p.goto(base,{waitUntil:"networkidle"});await p.waitForSelector("#authScreen:not([hidden])");await p.fill("#authEmail",email);await p.fill("#authPassword",password);await p.click("#signInButton");await p.waitForSelector("#projectsScreen:not([hidden])");return p}
let a,b,c,state,report;
try{
  a=await login();state=await a.evaluate(async title=>{const owner=cloudState.session.user.id,p=await cloudState.api.createProject({ownerId:owner,title}),p2=await cloudState.api.createProject({ownerId:owner,title:`${title} B`}),made=await cloudState.characterApi.createCharacterAndAttach(p.id,0,{name:"Image A",baseProfile:{}},{});if(!made.ok)return {error:made};const character=made.data.character,pc=made.data.project_character,id=crypto.randomUUID(),bytes=new TextEncoder().encode('<svg xmlns="http://www.w3.org/2000/svg" width="120" height="240"><rect width="120" height="240" fill="tomato"/></svg>'),file=new File([bytes],"portrait.png",{type:"image/png"}),photo={id,crop:{x:.25,y:.75,zoom:1.6},alt:"portrait",caption:"original",future:{keep:true}};const uploaded=await cloudState.imageApi.uploadImage({characterId:character.id,photoId:id,file,photo,scope:"global",expectedRevision:character.revision,isPrimary:true});const attached=await cloudState.characterApi.attachProjectCharacter(p2.id,character.id,0,{}),projectPhotoId=crypto.randomUUID(),projectFile=new File([bytes],"override.png",{type:"image/png"}),projectPhoto={id:projectPhotoId,crop:{x:.8,y:.2,zoom:2.1},caption:"project override"},projectUploaded=await cloudState.imageApi.uploadImage({characterId:character.id,projectCharacterId:attached.data.id,photoId:projectPhotoId,file:projectFile,photo:projectPhoto,scope:"project",expectedRevision:attached.revision,isPrimary:true});return {projectId:p.id,projectBId:p2.id,characterId:character.id,projectCharacterId:pc.id,projectBCharacterId:attached.data.id,photoId:id,projectPhotoId,path:uploaded.storagePath,projectPath:projectUploaded.storagePath,uploaded,projectUploaded}},title);
  assert(state.uploaded?.ok&&state.projectUploaded?.ok,`upload failed ${JSON.stringify(state)}`);
  b=await login();const proofB=await b.evaluate(async s=>{const rows=await cloudState.imageApi.listImages(s.characterId,s.projectCharacterId),signed=await cloudState.imageApi.signedUrl(s.path);const response=signed.ok?await fetch(signed.url):null;return {rows,signedOk:signed.ok,status:response?.status,bytes:response?await response.arrayBuffer().then(x=>x.byteLength):0}},state);
  assert(proofB.rows.ok&&proofB.rows.data.length===1,"Browser B metadata missing");assert(proofB.rows.data[0].crop.x===.25&&proofB.rows.data[0].is_primary,"Browser B crop/primary mismatch");assert(proofB.signedOk&&proofB.status===200&&proofB.bytes>0,"Browser B original unavailable");const scoped=await b.evaluate(async s=>cloudState.imageApi.listImages(s.characterId,s.projectBCharacterId),state);assert(scoped.ok&&scoped.data.length===2&&scoped.data.some(x=>x.id===state.projectPhotoId&&x.crop.x===.8),"project image scope failed");
  c=await login();const proofC=await c.evaluate(async s=>{const rows=await cloudState.imageApi.listImages(s.characterId,s.projectCharacterId),signed=await cloudState.imageApi.signedUrl(s.path);return {count:rows.data?.length,crop:rows.data?.[0]?.crop,signed:signed.ok,code:rows.code}},state);assert(proofC.count===1&&Number(proofC.crop.zoom)===1.6&&proofC.signed,`Browser C fresh read failed: ${JSON.stringify(proofC)}`);
  const stale=await b.evaluate(async s=>{const rows=await cloudState.imageApi.listImages(s.characterId,s.projectCharacterId),rev=rows.data[0].revision,winner=await cloudState.imageApi.updateImage(s.photoId,rev,{crop:{x:.7,y:.2,zoom:2}}),loser=await cloudState.imageApi.updateImage(s.photoId,rev,{crop:{x:.1,y:.1,zoom:1}}),after=await cloudState.imageApi.listImages(s.characterId,s.projectCharacterId);return {winner,loser,crop:after.data[0].crop}},state);assert(stale.winner.ok&&stale.loser.code==="CHARACTER_IMAGE_REVISION_CONFLICT"&&stale.crop.x===.7,"stale writer contract failed");
  const anonymous=await browser.newContext();contexts.push(anonymous);const p=await anonymous.newPage();await p.goto(base+"?local=1");const foreign=await p.evaluate(async path=>{const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/+esm"),client=createClient("https://crchibwumcuuqhkabmfj.supabase.co","sb_publishable_XF0Jk1qKpK4OgW8NAyaj7g_IuAdH8RT");const r=await client.storage.from("character-images").createSignedUrl(path,60);return {data:r.data,error:!!r.error}},state.path);assert(foreign.error&&!foreign.data,"anonymous signed access succeeded");
  report={browserA:true,browserB:true,browserC:true,privateOriginal:true,crop:true,primary:true,projectScope:true,staleConflict:true,anonymousBlocked:true};
}finally{
  try{if(b&&state?.photoId){await b.evaluate(async s=>{const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/+esm"),client=createClient("https://crchibwumcuuqhkabmfj.supabase.co","sb_publishable_XF0Jk1qKpK4OgW8NAyaj7g_IuAdH8RT");for(const path of [s.path,s.projectPath])await client.storage.from("character-images").remove([path]);await client.from("character_images").delete().in("id",[s.photoId,s.projectPhotoId]);await client.from("projects").delete().in("id",[s.projectId,s.projectBId]);await client.from("characters").delete().eq("id",s.characterId)},state)}}finally{for(const x of contexts)await x.close();await browser.close()}
}
console.log(JSON.stringify({ok:true,...report}));
