import assert from "node:assert/strict";
import crypto from "node:crypto";
import {createRequire} from "node:module";
import {createClient} from "@supabase/supabase-js";
import {parseProjectJson,prepareProject} from "../js/migrations.js";

const require=createRequire("C:/Users/tadan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/");
const {chromium}=require("playwright"),base=process.env.AUTHOR_WORKSPACE_URL||"http://localhost:8000/";
const email=process.env.CLOUD_TEST_EMAIL,password=process.env.CLOUD_TEST_PASSWORD;
if(!email||!password){console.log("local cloud migration production-wizard acceptance skipped: credentials are not configured");process.exit(0)}
class UnusedRealtimeTransport{}
const client=createClient("https://crchibwumcuuqhkabmfj.supabase.co","sb_publishable_XF0Jk1qKpK4OgW8NAyaj7g_IuAdH8RT",{auth:{persistSession:false,autoRefreshToken:false},realtime:{transport:UnusedRealtimeTransport}});
const marker=crypto.randomBytes(7).toString("hex"),targetTitle=`AW CP3B ${marker}`,mappedName=`Mapped ${marker}`,sourceTitle=`Legacy ${marker}`;
const png="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
const source={version:11,title:sourceTitle,acceptanceMarker:marker,characters:[
  {id:"char-a",name:"Alice",surname:"Created",role:"lead"},{id:"char-b",name:mappedName,surname:"Local",role:"support"},{id:"char-c",name:mappedName,surname:"Candidate",role:"support"}
],profiles:{
  "char-a":{name:"Alice",surname:"Created",profession:"Writer",description:"created profile",favorites:["tea","rain"],hobbies:["walking","reading"],features:"",photos:[{id:"photo-global",source:{kind:"data-url",value:png},crop:{x:.2,y:.3,zoom:1.4},alt:"Alice original",caption:"Global portrait",isPrimary:true,sortOrder:0,acceptanceMarker:marker}],primaryPhotoId:"photo-global",initialRelations:{"char-b":"trust"}},
  "char-b":{name:mappedName,surname:"Local",profession:"Local editor",description:"project override",favorites:["local favorite"],hobbies:["local hobby"],photos:[{id:"photo-project",source:{kind:"data-url",value:png},crop:{x:.6,y:.4,zoom:1.8},alt:"Mapped original",caption:"Project portrait",isPrimary:true,sortOrder:0,acceptanceMarker:marker}],primaryPhotoId:"photo-project",initialRelations:{}},
  "char-c":{name:mappedName,surname:"Candidate",profession:null,description:"",favorites:[],hobbies:["music"],photos:[],primaryPhotoId:"",initialRelations:{}}
},characterLinks:[
  {id:"link-global",fromCharacterId:"char-a",toCharacterId:"char-b",category:"other",type:"custom",reverseType:"custom",customLabel:"mentor",reverseCustomLabel:"student",structureKind:"other",metadata:{acceptanceMarker:marker}},
  {id:"link-project",fromCharacterId:"char-b",toCharacterId:"char-c",category:"family",type:"sibling",reverseType:"sibling",structureKind:"biological",metadata:{acceptanceMarker:marker}}
],chapters:[{id:"chapter-unassigned",title:"Без главы"},{id:"chapter-a",title:"Chapter A",position:1000},{id:"chapter-b",title:"Chapter B",position:2000}],locations:[{id:"loc-a",name:"Home",description:"A"},{id:"loc-b",name:"Station",description:"B"}],tags:[{id:"tag-a",name:"Mystery"},{id:"tag-b",name:"Night"},{id:"tag-c",name:"Memory"}],scenes:[
  {id:"scene-1",chapterId:"chapter-a",locationId:"loc-a",tags:["tag-a"],title:"A One",sceneText:"Alpha",date:"2026-08-01",time:"09:15",status:"fixed",writingStatus:"draft",included:true,dateReview:false,people:{"char-a":{action:"speaks",relationChanges:{},visibleRelations:["char-b"]}}},
  {id:"scene-2",chapterId:"chapter-a",locationId:"loc-b",tags:["tag-b","tag-c"],title:"A Two",sceneText:"Beta",date:"2026-08-02",time:"10:30",status:"floating",writingStatus:"edit1",included:true,dateReview:true,people:{"char-b":{action:"listens",relationChanges:{"char-a":"doubt"},visibleRelations:["char-a"]}}},
  {id:"scene-3",chapterId:"chapter-b",locationId:"loc-a",tags:["tag-c"],title:"B One",sceneText:"Gamma",date:"",time:"",status:"fixed",writingStatus:"edit2",included:false,dateReview:true,people:{"char-c":{action:"waits",relationChanges:{},visibleRelations:[]}}},
  {id:"scene-4",chapterId:"chapter-b",locationId:"",tags:[],title:"B Two",sceneText:"Delta",date:"2026-08-04",time:"",status:"floating",writingStatus:"final",included:true,dateReview:false,people:{"char-a":{action:"leaves",relationChanges:{"char-b":""},visibleRelations:["char-b"]}}},
  {id:"scene-5",chapterId:"chapter-unassigned",locationId:"loc-b",tags:["tag-a","tag-b"],title:"Unassigned",sceneText:"Epsilon",date:"",time:"",status:"floating",writingStatus:"plan",included:false,dateReview:true,people:{}}
]};
const sourceBefore=JSON.stringify(source),parsedSource=parseProjectJson(sourceBefore),preparedSource=parsedSource.ok?prepareProject(parsedSource.value):null;assert.equal(parsedSource.ok,true,JSON.stringify(parsedSource));assert.equal(preparedSource.canApply,true,JSON.stringify(preparedSource));
const cleanup={projectId:null,characterIds:[],imageIds:[],paths:[]},contexts=[];let browserSession=null;
const must=async promise=>{const x=await promise;if(x.error)throw x.error;return x.data};
const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"});
async function login(page,{mobile=false}={}){if(mobile)await page.setViewportSize({width:390,height:760});await page.goto(base,{waitUntil:"networkidle"});await page.waitForSelector("#projectsScreen:not([hidden])")}
async function fresh(opts={}){const context=await browser.newContext();contexts.push(context);await context.addInitScript(({session,fixture,seed})=>{localStorage.setItem("sb-crchibwumcuuqhkabmfj-auth-token",JSON.stringify(session));if(seed)localStorage.setItem("novelTimelineV11",JSON.stringify(fixture))},{session:browserSession,fixture:source,seed:!!opts.seed});const page=await context.newPage();page.setDefaultTimeout(25000);await login(page,opts);return page}
const projectRow=(page)=>page.locator(".cloud-project",{has:page.getByText(targetTitle,{exact:true})});
const choose=(page,selector)=>page.locator(selector).evaluate(input=>{input.checked=true;input.dispatchEvent(new Event("change",{bubbles:true}))});
async function openTarget(page){await projectRow(page).getByRole("button",{name:"Открыть"}).click();await page.waitForSelector('body[data-app-state="workspace"]');await page.waitForFunction(id=>globalThis.cloudProjectSync?.projectId===id&&globalThis.cloudProjectSync?.confirmedProject?.scenes?.length===5,cleanup.projectId)}
const state=page=>page.evaluate(()=>({revision:cloudProjectSync.revision,data:cloudProjectSync.confirmedProject,cacheKeys:Object.keys(localStorage)}));
let report;
try{
  const auth=await must(client.auth.signInWithPassword({email,password})),ownerId=auth.user.id;browserSession=auth.session;
  const target=await must(client.from("projects").insert({owner_id:ownerId,title:targetTitle}).select("id,revision").single());cleanup.projectId=target.id;assert.equal(target.revision,0);
  const mapped=await must(client.rpc("create_character",{character_name:mappedName,character_surname:"Global",base_profile:{profession:"Global base",favorites:["global favorite"],hobbies:[],acceptanceMarker:marker}}));assert.equal(mapped.ok,true);cleanup.characterIds.push(mapped.data.id);const mappedId=mapped.data.id;
  const pre=await must(client.rpc("get_local_project_import_snapshot",{target_project_id:target.id}));assert.equal(pre.ok,true);assert.equal(pre.data.scenes.length,0);assert.equal(pre.revision,0);
  const a=await fresh({seed:true}),rpcTrace=[];a.on("response",async response=>{if(/\/rpc\/(preflight_local_project_import|import_local_project_content|get_local_project_import_snapshot)/.test(response.url()))rpcTrace.push({url:response.url().split("/rpc/")[1],status:response.status(),body:(await response.text()).slice(0,3000)})});const seeded=await a.evaluate(()=>({raw:localStorage.getItem("novelTimelineV11"),hidden:document.getElementById("openLocalCloudMigration")?.hidden,startup:globalThis.startupLoadInfo?.status}));assert(seeded.raw,`legacy fixture disappeared: ${JSON.stringify(seeded)}`);assert.equal(JSON.parse(seeded.raw).title,sourceTitle);assert.equal(seeded.hidden,false,`migration entry hidden: ${JSON.stringify({...seeded,raw:"present"})}`);
  await a.locator("#openLocalCloudMigration").evaluate(button=>button.click());await a.waitForSelector("#localCloudMigrationModal",{state:"visible"});
  await a.selectOption("#migrationSource","novelTimelineV11");await a.selectOption("#migrationTarget",target.id);await a.click("#migrationPreviewButton");
  assert.equal(await a.locator("#migrationConfirmStep").isEnabled(),false);const previewText=await a.locator("#migrationWizardBody").innerText();for(const token of ["3персонажей","5сцен","2глав","2локаций","3тегов","2структурных связей","2изображений","Нужно исправить","Обратите внимание"])assert(previewText.replace(/\s/g,"").includes(token.replace(/\s/g,"")),`preview missing ${token}`);
  await choose(a,'input[name="character-char-a"][value="new"]');await a.locator('select[aria-label="Существующий персонаж для '+mappedName+'"]').first().selectOption(mappedId);await choose(a,'input[name="character-char-c"][value="new"]');
  await choose(a,'input[name="link-link-global"][value="global"]');await choose(a,'input[name="link-link-project"][value="project"]');await choose(a,'input[name="image-photo-global"][value="global"]');await choose(a,'input[name="image-photo-project"][value="project"]');
  assert.equal(await a.locator("#migrationConfirmStep").isEnabled(),true);assert((await a.locator("#migrationWizardBody").innerText()).replace(/\s/g,"").includes("4измененийотношений"));const beforeObjects=await client.storage.from("character-images").list(`${ownerId}/characters`,{limit:100});assert.equal(beforeObjects.error,null);
  await a.click("#migrationConfirmStep");const confirmation=await a.locator("#migrationWizardBody").innerText();assert(confirmation.includes(sourceTitle)&&confirmation.includes(targetTitle)&&confirmation.includes("Локальная копия проекта останется"));
  await a.click("#executeMigration");assert.equal(await a.locator("#localCloudMigrationModal").getAttribute("data-close-blocked"),"true");try{await a.getByRole("heading",{name:"Проект перенесён в облако"}).waitFor({timeout:60000})}catch(error){throw new Error(`migration result timeout: ${await a.locator("#migrationWizardTitle").innerText()} | ${await a.locator("#migrationWizardBody").innerText()} | RPC ${JSON.stringify(rpcTrace)} | ${error.message}`)}assert.equal(JSON.stringify(await a.evaluate(()=>JSON.parse(localStorage.getItem("novelTimelineV11")))),sourceBefore);
  await a.getByRole("button",{name:"Открыть облачный проект"}).click();await a.waitForSelector('body[data-app-state="workspace"]');await a.waitForFunction(()=>globalThis.cloudProjectSync?.confirmedProject?.scenes?.length===5);const sa=await state(a);assert.equal(sa.revision,1);
  const clearEmptyStartupLocal=page=>page.evaluate(()=>{const raw=localStorage.getItem("novelTimelineV11"),value=raw?JSON.parse(raw):null;if(value&&((value.characters||[]).length||(value.scenes||[]).length||Object.values(value.profiles||{}).some(profile=>(profile.photos||[]).length)))return {ok:false};localStorage.removeItem("novelTimelineV11");return {ok:true,keys:Object.keys(localStorage)}});
  const b=await fresh(),bClean=await clearEmptyStartupLocal(b);assert(bClean.ok&&!bClean.keys.some(k=>k.startsWith("authorWorkspace:project:")),`B cache not empty: ${JSON.stringify(bClean)}`);await openTarget(b);const sb=await state(b);
  const c=await fresh(),cClean=await clearEmptyStartupLocal(c);assert(cClean.ok&&!cClean.keys.some(k=>k.startsWith("authorWorkspace:project:")),`C cache not empty: ${JSON.stringify(cClean)}`);await openTarget(c);const sc=await state(c);
  for(const snapshot of [sa,sb,sc]){assert.equal(snapshot.data.scenes.length,5);assert.equal(snapshot.data.characters.length,3);assert.deepEqual(snapshot.data.profiles[mappedId].favorites,["local favorite"]);assert.equal(snapshot.data.characterLinks.length,2);assert.equal(snapshot.data.profiles[mappedId].photos.length,1)}
  const authoritative=await must(client.rpc("get_local_project_import_snapshot",{target_project_id:target.id})),d=authoritative.data;assert.equal(authoritative.revision,1);assert.deepEqual({characters:d.project_characters.length,chapters:d.chapters.length,locations:d.locations.length,tags:d.tags.length,scenes:d.scenes.length,sceneTags:d.scene_tags.length,sceneCharacters:d.scene_characters.length,relations:d.project_character_relations.length,changes:d.scene_relation_changes.length,links:d.character_links.length,images:d.character_images.length},{characters:3,chapters:2,locations:2,tags:3,scenes:5,sceneTags:6,sceneCharacters:4,relations:1,changes:3,links:2,images:2});
  assert.equal(d.scenes.find(x=>x.title==="Unassigned").chapter_id,null);assert.equal(JSON.stringify(d).includes("data:image/"),false);assert.equal(JSON.stringify(d).includes("base64"),false);assert.equal(d.character_links.filter(x=>x.project_id===null).length,1);assert.equal(d.character_links.filter(x=>x.project_id===target.id).length,1);assert.equal(d.character_images.filter(x=>x.project_character_id===null).length,1);assert.equal(d.character_images.filter(x=>x.project_character_id!==null).length,1);
  const mappedBase=await must(client.from("characters").select("base_profile").eq("id",mappedId).single());assert.deepEqual(mappedBase.base_profile,{profession:"Global base",favorites:["global favorite"],hobbies:[],acceptanceMarker:marker});const mappedPc=d.project_characters.find(x=>x.character_id===mappedId);assert.equal(mappedPc.overrides.profession,"Local editor");
  cleanup.characterIds.push(...d.project_characters.map(x=>x.character_id).filter(id=>id!==mappedId));cleanup.imageIds.push(...d.character_images.map(x=>x.id));cleanup.paths.push(...d.character_images.map(x=>x.storage_path));for(const image of d.character_images){assert(image.storage_path.startsWith(`${ownerId}/characters/${image.character_id}/${image.id}/original.`));const download=await client.storage.from("character-images").download(image.storage_path);assert.equal(download.error,null);assert((await download.data.arrayBuffer()).byteLength>0)}
  const retry=await client.rpc("preflight_local_project_import",{target_project_id:target.id,expected_revision:0,migration_attempt_id:crypto.randomUUID(),import_payload:{}});assert.equal(retry.error,null);assert(["REVISION_CONFLICT","TARGET_NOT_EMPTY"].includes(retry.data.code));
  const mobile=await fresh({seed:true,mobile:true});await mobile.locator("#openLocalCloudMigration").evaluate(button=>button.click());await mobile.waitForSelector("#localCloudMigrationModal",{state:"visible"});assert(await mobile.evaluate(()=>document.getElementById("localCloudMigrationModal").scrollWidth<=document.documentElement.clientWidth));await mobile.keyboard.press("Escape");
  report={browserA:true,browserB:true,browserC:true,preview:{characters:3,scenes:5,chapters:2,locations:2,tags:3,links:2,relations:4,images:2},revision:{before:0,after:1},mappedBasePreserved:true,overrides:true,noBase64:true,storage:true,localSourcePreserved:true,mobile:true,idempotencyGuard:retry.data.code};
}finally{
  for(const context of contexts)await context.close();await browser.close();
  for(const path of cleanup.paths){const x=await client.storage.from("character-images").remove([path]);if(x.error)console.error("cleanup storage",x.error.message)}
  if(cleanup.imageIds.length){const x=await client.from("character_images").delete().in("id",cleanup.imageIds);if(x.error)console.error("cleanup images",x.error.message)}
  if(cleanup.projectId){const x=await client.from("projects").delete().eq("id",cleanup.projectId);if(x.error)console.error("cleanup project",x.error.message)}
  if(cleanup.characterIds.length){const x=await client.from("characters").delete().in("id",[...new Set(cleanup.characterIds)]);if(x.error)console.error("cleanup characters",x.error.message)}
  const [projects,characters,images,attempts]=await Promise.all([client.from("projects").select("id",{count:"exact",head:true}).eq("title",targetTitle),cleanup.characterIds.length?client.from("characters").select("id",{count:"exact",head:true}).in("id",[...new Set(cleanup.characterIds)]):Promise.resolve({count:0}),cleanup.imageIds.length?client.from("character_images").select("id",{count:"exact",head:true}).in("id",cleanup.imageIds):Promise.resolve({count:0}),cleanup.projectId?client.from("local_project_import_attempts").select("id",{count:"exact",head:true}).eq("project_id",cleanup.projectId):Promise.resolve({count:0})]);
  let storageObjects=0;for(const path of cleanup.paths){const parts=path.split("/"),x=await client.storage.from("character-images").list(parts.slice(0,-1).join("/"),{search:parts.at(-1)});if(!x.error)storageObjects+=x.data.filter(v=>v.name===parts.at(-1)).length}const cleanupReport={projects:projects.count??-1,characters:characters.count??-1,characterImages:images.count??-1,attempts:attempts.count??-1,storageObjects,projectId:cleanup.projectId,characterIds:[...new Set(cleanup.characterIds)],imageIds:cleanup.imageIds};console.log(JSON.stringify({acceptance:report,cleanup:cleanupReport}));assert.equal(cleanupReport.projects,0);assert.equal(cleanupReport.attempts,0);assert.equal(cleanupReport.storageObjects,0);await client.auth.signOut();
}
